#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(S: str) -> str:
def solve(S):
    # ABC001 から ABC349 まで ABC316 を除く 配列を作成
    cont = ["ABC%03d" % x for x in range(1,316)] + ["ABC%03d" % x for x in range(317,350)]
    # 配列にあればYES,無ければNO
    a = YES if S in cont else NO
    return a

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    #S = "ABC350"

    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
