#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, R: str, C: str) -> Tuple[str, List[str]]:
def solve(N, R, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    R = input()
    C = input()
    Yes, A = solve(N, R, C)
    print(Yes)
    for i in range(N):
        print(A[i])

if __name__ == '__main__':
    main()
