#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, P: List[int], S: str) -> int:
def solve(N, P, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    P = [None for _ in range(N)]
    for i in range(N):
        P[i] = int(next(tokens))
    S = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, P, S)
    print(a)

def main2():
    with open("./abc349/abc349_a/test/sample-3.in") as f:
        tokens = iter(f.read().split())
    N = int(next(tokens))
    P = [None for _ in range(N)]
    for i in range(N):
        P[i] = int(next(tokens))
    S = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, P, S)
    print(a)

if __name__ == '__main__':
    main()
