#!/usr/bin/env python3
# from typing import *

# def solve(N: int, Q: int, T: List[int]) -> int:
def solve(N, Q, T):
    # 歯N個 すべて1(あり) の状態の配列を作成
    th = [1 for x in range(N)]
    # Tの番号を確認し,該当する歯があれば無しに,なければありに
    for t in T:
        th[t-1] = 0 if th[t-1] == 1 else 1
    a = sum(th)
    return a

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    T = [None for _ in range(Q)]
    for i in range(Q):
        T[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, Q, T)
    print(a)

if __name__ == '__main__':
    #a = solve(10, 5, [1,3,4,4,5])
    main()
