#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, K: int, u: List[int], v: List[int]) -> Tuple[str, List[str]]:
def solve(N, K, u, v):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    u = [None for _ in range(N - 1)]
    v = [None for _ in range(N - 1)]
    for i in range(N - 1):
        u[i], v[i] = map(int, input().split())
    Yes, P = solve(N, K, u, v)
    print(Yes)
    print(*[P[i] for i in range(N)])

if __name__ == '__main__':
    main()
