#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def gen():
    N = random.randint(1, 100000)  # TODO: edit here
    P = [None for _ in range(N)]
    #K = random.randint(1, 10 ** 9)  # TODO: edit here
    K = random.randint(1, N)  # TODO: edit here

    for i in range(N):
    #    P[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        P[i] = i+1
    
    random.shuffle(P)

    print(N, K)
    #print(*[P[i] for i in range(N)])

    return N,K,P

if __name__ == "__main__":
    gen()
