#!/usr/bin/env python3
# from typing import *

# def solve(N: int, A: List[int], C: List[int]) -> Tuple[int, List[int]]:
#def solve(N, A, C):
def solve(N, A):

    A = sorted(A)
    #B = [A[0]]
    b = A[0][1]
    C = [A[0][2]]

    for a in A:
        if b < a[1]:
            b = a[1]
            C.append(a[2])

    C = sorted(C)
    print(len(C))
    if len(C) > 0:
        s = "%d" % C[0]
        for c in C[1:]:
            s += " %d" % c
        print(s)
    return
    #pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = []
    for i in range(N):
        s,c = list(map(int, input().split()))
        A.append([c,s,i+1])
    solve(N, A)

def main2():
    with open("./abc354/abc354_c/test/sample-1.in") as f:
        a = f.read().split("\n")
    N = int(a[0])
    A = []
    C = []
    for i in range(1,N+1):
        s,c = list(map(int, a[i].split()))
        A.append([c,s,i]) # コスト,強さ,インデックス
    solve(N, A)

if __name__ == '__main__':
    main()
