#!/usr/bin/env python3
# from typing import *

def solve(a, b):
    a2 = sum(a)
    b2 = sum(b)
    c = a2 - b2 + 1
    return c
    #pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = list(map(int, input().split()))
    b = list(map(int, input().split()))
    c = solve(a, b)
    print(c)

def main2():
    with open("./abc351/abc351_a/test/sample-2.in") as f:
        a, b = f.read().split("\n")[:2]

    a = list(map(int, a.split()))
    b = list(map(int, b.split()))

    c = solve(a, b)
    print(c)

if __name__ == '__main__':
    main2()
