#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, C: List[int], A: List[int], L: List[List[int]]) -> int:
def solve(N, M, C, A, L):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    C = [None for _ in range(N)]
    A = [None for _ in range(M)]
    L = [[None for _ in range(N)] for _ in range(M)]
    for i in range(N):
        C[i] = int(next(tokens))
    for i in range(M):
        A[i] = int(next(tokens))
    for j in range(M):
        for i in range(N):
            L[j][i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, C, A, L)
    print(a)

if __name__ == '__main__':
    main()
