#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, int M, const std::vector<int64_t> &C, const std::vector<int64_t> &A, const std::vector<std::vector<int64_t> > &L) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<int64_t> C(N);
    std::cin >> M;
    std::vector<int64_t> A(M);
    std::vector<std::vector<int64_t> > L(M, std::vector<int64_t>((N)));
    REP (i, N) {
        std::cin >> C[i];
    }
    REP (i, M) {
        std::cin >> A[i];
    }
    REP (j, M) {
        REP (i, N) {
            std::cin >> L[j][i];
        }
    }
    auto ans = solve(N, M, C, A, L);
    std::cout << ans << '\n';
    return 0;
}
