#!/usr/bin/env python3
# from typing import *



# def solve(N: int, K: int) -> Tuple[List[str], List[str], List[str]]:
def solve(N, K):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    x, y, z = solve(N, K)
    for i in range(K):
        print(x[i], y[i], z[i])

if __name__ == '__main__':
    main()
