#!/usr/bin/env python3
# from typing import *

# def solve(N: int, A: List[int], B: List[int]) -> int:
#def solve(N, A, B):
def solve(A, B):
    max = 0
    for a, b in zip(A, B):
        if max < b-a: max = b-a
    return sum(A)+max

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    #with open("./abc352/abc352_c/test/sample-3.in") as f:
    #    a = f.read().split("\n")

    N = int(input())
    #N = int(a[0])

    AB = []
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
        #A[i], B[i] = list(map(int, a[i+1].split()))
        #AB.append(list(map(int, a[i+1].split())))

    #a = solve(N, A, B)
    a = solve(A, B)
    print(a)

if __name__ == '__main__':
    main()
