#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int64_t N, int64_t C, int M, const std::vector<int64_t> &T, const std::vector<int64_t> &P) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, C;
    int M;
    std::cin >> N >> C >> M;
    std::vector<int64_t> T(M), P(M);
    REP (i, M) {
        std::cin >> T[i] >> P[i];
    }
    auto ans = solve(N, C, M, T, P);
    std::cout << ans << '\n';
    return 0;
}
