#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, A: List[int]) -> int:
def solve(N, a):
    sm = 0
    for i in range(N-1):
        for j in range(i+1,N):
            #print(i,j)
            #sm += (a[i]+a[j]) % 100000000
            s = int(str(a[i]+a[j])[-8:])
            sm += s
    return sm

    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A)
    print(a)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main2():
    with open("./abc353/abc353_d/test/sample-2.in") as f:
        a = f.read().split("\n")
    N = int(a[0])
    aa = list(map(int, a[1].split()))
    a = solve(N, aa)
    print(a)

if __name__ == '__main__':
    main2()
