#!/usr/bin/env python3
# from typing import *

# def solve(N: str, A: List[List[str]], B: List[List[str]]) -> Tuple[int, int]:
def solve(a1, b1):
    for i in range(len(a1)):
        if a1[i] != b1[i]:
            a2 = a1[i]
            b2 = b1[i]
            for j in range(len(a2)):
                if a2[j] != b2[j]:
                    s = "%d %d" % (i+1,j+1)
                    print(s)
                    break

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    a1 = []
    b1 = []
    for i in range(n):
        a1.append(input())
    for i in range(n):
        b1.append(input())
    solve(a1, b1)

def main2():
    with open("./abc351/abc351_b/test/sample-2.in") as f:
        #tokens = iter(f.read().split())
        alist = f.read().split() 

    n = int(alist[0])
    a1 = []
    b1 = []
    for i in range(n):
        a1.append(alist[1+i])
    for i in range(n):
        b1.append(alist[1+n+i])
    solve(a1, b1)

if __name__ == '__main__':
    main2()
