#!/usr/bin/env python3
# from typing import *



# def solve(L: int, R: int) -> Tuple[int, List[int], List[int]]:
def solve(L, R):
    a = L
    b = 0
    l = []
    r = []
    while(1):
        l.append(a)
        b = [int(x) for x in list(bin(a)[2:])]
        if b[0] == 1 and sum(b) == 1:
            l.append(b)

        b = list(bin(a))
        if a == 1:
            break

    M = 1
    l = [1,2]
    r = [3,4]
    return M, l, r
    #pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    #L, R = map(int, input().split())
    with open("./abc349/abc349_d/test/sample-3.in") as f:
        L, R = map(int, f.read().split())
    M, l, r = solve(L, R)
    print(M)
    for i in range(M):
        print(l[i], r[i])

if __name__ == '__main__':
    main()
